/**
 * 🔐 Privilege Auditor Dashboard — Interactive App Logic
 */

// ─── State ───────────────────────────────────────────────
let allUsers = [];
let currentFilter = 'all';
let currentSort = { key: 'days_inactive', dir: 'desc' };
let currentData = null;

const SYSTEM_NAMES = {
    linux:            { label: 'Linux',  emoji: '🐧' },
    active_directory: { label: 'AD',     emoji: '🏢' },
    aws_iam:          { label: 'AWS IAM',emoji: '☁️' },
};

const RISK_ORDER = { CRITICAL: 4, HIGH: 3, MEDIUM: 2, LOW: 1 };

// ─── Data Loading ─────────────────────────────────────────
async function loadData() {
    // Try to load from reports/dashboard_data.json (generated by Python)
    try {
        const response = await fetch('../reports/dashboard_data.json');
        if (response.ok) {
            const data = await response.json();
            processData(data);
            return;
        }
    } catch (e) {}

    // Fallback: load embedded demo data
    console.log('Loading demo data...');
    processData(getDemoData());
}

function processData(data) {
    currentData = data;
    allUsers = [];

    const systems = data.systems || [];

    // Flatten all users from all systems
    for (const report of systems) {
        const system = report.system;
        const users = report.users || [];
        for (const user of users) {
            allUsers.push({ ...user, system });
        }
    }

    // Update stats
    updateStats(systems);
    renderCharts(systems);
    renderTable();
    updateLogSection(data.log_analysis);
    updateScanTime(data.generated_at);
}

function updateStats(systems) {
    let totalPrivileged = 0, totalInactive = 0, totalCritical = 0;

    for (const r of systems) {
        const s = r.summary || {};
        totalPrivileged += s.total_privileged_users || 0;
        totalInactive   += (s.inactive_users || s.inactive_privileged_users || 0);
        totalCritical   += s.critical_users || 0;
    }

    animateNumber('num-critical',   totalCritical);
    animateNumber('num-inactive',   totalInactive);
    animateNumber('num-privileged', totalPrivileged);
    animateNumber('num-systems',    systems.length);
}

function animateNumber(id, target) {
    const el = document.getElementById(id);
    if (!el) return;
    const start = parseInt(el.textContent) || 0;
    const duration = 600;
    const startTime = performance.now();

    function update(now) {
        const elapsed = now - startTime;
        const progress = Math.min(elapsed / duration, 1);
        const eased = 1 - Math.pow(1 - progress, 3); // ease-out cubic
        el.textContent = Math.round(start + (target - start) * eased);
        if (progress < 1) requestAnimationFrame(update);
    }
    requestAnimationFrame(update);
}

function updateScanTime(ts) {
    const el = document.getElementById('scan-time-text');
    if (!el || !ts) return;
    try {
        const d = new Date(ts);
        el.textContent = d.toLocaleString('vi-VN');
    } catch (e) {
        el.textContent = ts;
    }
}

// ─── Charts ───────────────────────────────────────────────
let riskChart, inactiveChart, systemChart;

function renderCharts(systems) {
    renderRiskChart();
    renderInactiveChart();
    renderSystemChart(systems);
}

function renderRiskChart() {
    const counts = { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0 };
    for (const u of allUsers) {
        const r = u.risk_level || 'LOW';
        if (counts[r] !== undefined) counts[r]++;
    }

    const ctx = document.getElementById('riskChart');
    if (!ctx) return;

    if (riskChart) riskChart.destroy();

    riskChart = new Chart(ctx, {
        type: 'doughnut',
        data: {
            labels: ['Critical', 'High', 'Medium', 'Low'],
            datasets: [{
                data: [counts.CRITICAL, counts.HIGH, counts.MEDIUM, counts.LOW],
                backgroundColor: ['#ef4444cc', '#f97316cc', '#eab308cc', '#22c55ecc'],
                borderColor:     ['#ef4444',   '#f97316',   '#eab308',   '#22c55e'],
                borderWidth: 1.5,
                hoverOffset: 6,
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            cutout: '68%',
            plugins: {
                legend: { display: false },
                tooltip: {
                    callbacks: {
                        label: ctx => ` ${ctx.label}: ${ctx.raw} users`
                    }
                }
            }
        }
    });

    // Legend
    const legendEl = document.getElementById('risk-legend');
    if (legendEl) {
        const colors = { Critical: '#ef4444', High: '#f97316', Medium: '#eab308', Low: '#22c55e' };
        const vals = { Critical: counts.CRITICAL, High: counts.HIGH, Medium: counts.MEDIUM, Low: counts.LOW };
        legendEl.innerHTML = Object.entries(vals).map(([k, v]) =>
            `<div class="legend-item">
                <div class="legend-dot" style="background:${colors[k]}"></div>
                <span>${k}: ${v}</span>
            </div>`
        ).join('');
    }
}

function renderInactiveChart() {
    const ctx = document.getElementById('inactiveChart');
    if (!ctx) return;

    // Group by days inactive ranges
    const ranges = { '0-30': 0, '31-60': 0, '61-90': 0, '91-180': 0, '180+': 0 };
    for (const u of allUsers) {
        const d = u.days_inactive || 0;
        if (d <= 30) ranges['0-30']++;
        else if (d <= 60) ranges['31-60']++;
        else if (d <= 90) ranges['61-90']++;
        else if (d <= 180) ranges['91-180']++;
        else ranges['180+']++;
    }

    if (inactiveChart) inactiveChart.destroy();

    inactiveChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: Object.keys(ranges),
            datasets: [{
                label: 'Số admin',
                data: Object.values(ranges),
                backgroundColor: ['#22c55e99', '#eab30899', '#f9731699', '#ef444499', '#b91c1c99'],
                borderColor:     ['#22c55e',   '#eab308',   '#f97316',   '#ef4444',   '#b91c1c'],
                borderWidth: 1,
                borderRadius: 6,
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: { display: false },
                tooltip: { callbacks: { label: ctx => ` ${ctx.raw} tài khoản` } }
            },
            scales: {
                x: {
                    grid: { color: 'rgba(255,255,255,0.04)' },
                    ticks: { color: '#94a3b8', font: { size: 11 } }
                },
                y: {
                    grid: { color: 'rgba(255,255,255,0.04)' },
                    ticks: { color: '#94a3b8', font: { size: 11 }, stepSize: 1 },
                    beginAtZero: true,
                }
            }
        }
    });
}

function renderSystemChart(systems) {
    const ctx = document.getElementById('systemChart');
    if (!ctx) return;

    const labels = systems.map(r => {
        const info = SYSTEM_NAMES[r.system] || { emoji: '🖥️', label: r.system };
        return `${info.emoji} ${info.label}`;
    });

    const privileged = systems.map(r => r.summary?.total_privileged_users || 0);
    const inactive   = systems.map(r => r.summary?.inactive_users || r.summary?.inactive_privileged_users || 0);
    const critical   = systems.map(r => r.summary?.critical_users || 0);

    if (systemChart) systemChart.destroy();

    systemChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels,
            datasets: [
                { label: 'Privileged', data: privileged, backgroundColor: '#6366f199', borderColor: '#6366f1', borderWidth: 1, borderRadius: 4 },
                { label: 'Inactive',   data: inactive,   backgroundColor: '#eab30899', borderColor: '#eab308', borderWidth: 1, borderRadius: 4 },
                { label: 'Critical',   data: critical,   backgroundColor: '#ef444499', borderColor: '#ef4444', borderWidth: 1, borderRadius: 4 },
            ]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: {
                    display: true,
                    labels: { color: '#94a3b8', font: { size: 11 }, boxWidth: 12, boxHeight: 12 }
                }
            },
            scales: {
                x: { grid: { color: 'rgba(255,255,255,0.04)' }, ticks: { color: '#94a3b8', font: { size: 11 } } },
                y: { grid: { color: 'rgba(255,255,255,0.04)' }, ticks: { color: '#94a3b8', font: { size: 11 }, stepSize: 1 }, beginAtZero: true }
            }
        }
    });
}

// ─── Table Rendering ──────────────────────────────────────
function renderTable() {
    const searchVal = document.getElementById('search-input')?.value.toLowerCase() || '';
    const systemFilter = document.getElementById('system-filter')?.value || 'all';

    let filtered = allUsers.filter(u => {
        const username = (u.username || u.sam_account || '').toLowerCase();
        const matchSearch = !searchVal || username.includes(searchVal);
        const matchRisk = currentFilter === 'all' || u.risk_level === currentFilter;
        const matchSystem = systemFilter === 'all' || u.system === systemFilter;
        return matchSearch && matchRisk && matchSystem;
    });

    // Sort
    filtered.sort((a, b) => {
        let va = a[currentSort.key], vb = b[currentSort.key];
        if (currentSort.key === 'risk_level') {
            va = RISK_ORDER[va] || 0;
            vb = RISK_ORDER[vb] || 0;
        }
        if (typeof va === 'string') va = va.toLowerCase();
        if (typeof vb === 'string') vb = vb.toLowerCase();
        if (va < vb) return currentSort.dir === 'asc' ? -1 : 1;
        if (va > vb) return currentSort.dir === 'asc' ? 1 : -1;
        return 0;
    });

    const tbody = document.getElementById('users-tbody');
    const countEl = document.getElementById('result-count');
    if (countEl) countEl.textContent = `${filtered.length} users`;

    if (filtered.length === 0) {
        tbody.innerHTML = `<tr><td colspan="8" style="text-align:center;padding:40px;color:var(--text-muted)">
            😴 Không tìm thấy kết quả phù hợp
        </td></tr>`;
        return;
    }

    tbody.innerHTML = filtered.map((u, idx) => {
        const username = u.username || u.sam_account || 'Unknown';
        const initials = username.slice(0, 2).toUpperCase();
        const sysInfo = SYSTEM_NAMES[u.system] || { emoji: '🖥️', label: u.system };
        const risk = u.risk_level || 'LOW';
        const days = u.days_inactive;
        const daysClass = days > 180 ? 'critical' : days > 60 ? 'high' : days > 30 ? 'medium' : days < 0 ? 'unknown' : 'low';
        const daysText = days < 0 ? 'Unknown' : `${days}d`;

        const lastLogin = (u.last_login || u.last_logon || '').substring(0, 10) || 'N/A';

        const privileges = [
            ...(u.privilege_source || u.privilege_groups || u.attached_policies || [])
        ].slice(0, 3);
        const privTags = privileges.map(p => `<span class="priv-tag">${p}</span>`).join('') || '—';

        const topAlert = (u.alerts || [])[0] || '—';
        const alertMore = u.alerts?.length > 1 ? ` <span style="color:var(--text-muted)">+${u.alerts.length - 1}</span>` : '';

        const riskEmoji = { CRITICAL: '🔴', HIGH: '🟠', MEDIUM: '🟡', LOW: '🟢' }[risk] || '⚪';

        return `<tr data-idx="${idx}" style="animation: fade-in-row 0.3s ease ${idx * 0.03}s both">
            <td>
                <div class="username-cell">
                    <div class="username-avatar">${initials}</div>
                    <span class="username-text">${username}</span>
                </div>
            </td>
            <td><span class="system-badge">${sysInfo.emoji} ${sysInfo.label}</span></td>
            <td><span class="days-cell ${daysClass}">${daysText}</span></td>
            <td><span class="risk-badge ${risk}">${riskEmoji} ${risk}</span></td>
            <td><span class="last-login-cell">${lastLogin}</span></td>
            <td><div class="privileges-cell">${privTags}</div></td>
            <td><div class="alerts-cell">${topAlert}${alertMore}</div></td>
            <td>
                <button class="btn-detail" onclick="showUserDetail(${JSON.stringify(u).replace(/"/g, '&quot;')})">
                    🔍 Chi tiết
                </button>
            </td>
        </tr>`;
    }).join('');
}

// ─── Filters & Sort ───────────────────────────────────────
function setFilter(filter, el) {
    currentFilter = filter;
    document.querySelectorAll('.chip').forEach(c => c.classList.remove('active'));
    el.classList.add('active');
    renderTable();
}

function filterTable() {
    renderTable();
}

function sortTable(key) {
    if (currentSort.key === key) {
        currentSort.dir = currentSort.dir === 'asc' ? 'desc' : 'asc';
    } else {
        currentSort.key = key;
        currentSort.dir = 'desc';
    }
    renderTable();
}

// ─── Log Section ──────────────────────────────────────────
function updateLogSection(log) {
    if (!log) return;

    const sudoEl  = document.getElementById('log-sudo');
    const sshEl   = document.getElementById('log-ssh');
    const bruteEl = document.getElementById('log-brute');

    if (sudoEl) sudoEl.textContent = log.total_sudo_events || 0;
    if (sshEl)  sshEl.textContent  = log.total_ssh_logins  || 0;

    const suspicious = log.suspicious_accounts || [];
    if (bruteEl) bruteEl.textContent = suspicious.length;

    const bruteForcedContainer = document.getElementById('brute-force-list');
    if (bruteForcedContainer && suspicious.length > 0) {
        const failed = log.failed_login_accounts || {};
        bruteForcedContainer.innerHTML = `
            <div class="brute-force-section">
                <h3>🚨 Tài Khoản Bị Brute Force Tấn Công</h3>
                ${suspicious.map(acc =>
                    `<div class="brute-item">
                        <span>⚠️</span>
                        <span class="brute-username">${acc}</span>
                        <span class="brute-count">${failed[acc] || 0} lần thất bại</span>
                    </div>`
                ).join('')}
            </div>`;
    }
}

// ─── User Detail Modal ────────────────────────────────────
function showUserDetail(user) {
    const modal = document.getElementById('modal-overlay');
    const title = document.getElementById('modal-title');
    const body  = document.getElementById('modal-body');

    const username = user.username || user.sam_account || 'Unknown';
    const risk = user.risk_level || 'LOW';
    const riskEmoji = { CRITICAL: '🔴', HIGH: '🟠', MEDIUM: '🟡', LOW: '🟢' }[risk] || '⚪';
    const sysInfo = SYSTEM_NAMES[user.system] || { emoji: '🖥️', label: user.system };

    title.innerHTML = `${riskEmoji} ${username} <span style="font-size:0.75rem;color:var(--text-secondary);font-weight:400">${sysInfo.emoji} ${sysInfo.label}</span>`;

    const fields = [
        ['Username', `<code style="font-family:monospace;color:var(--accent-light)">${username}</code>`],
        ['Hệ thống', `${sysInfo.emoji} ${sysInfo.label}`],
        ['Risk Level', `<span class="risk-badge ${risk}">${riskEmoji} ${risk}</span>`],
        ['Days Inactive', `${user.days_inactive >= 0 ? user.days_inactive + ' ngày' : 'Unknown'}`],
        ['Last Login', user.last_login || user.last_logon || 'N/A'],
        ['Email', user.email || 'N/A'],
        ['Account Enabled', user.account_enabled !== false ? '✅ Enabled' : '❌ Disabled'],
        ['MFA Active', user.mfa_active !== undefined ? (user.mfa_active ? '✅ Yes' : '❌ No') : 'N/A'],
        ['Full Admin Access', user.full_access || user.has_admin_access ? '⚠️ Yes' : 'No'],
        ['NOPASSWD Sudo', user.nopasswd ? '⚠️ Yes' : 'No'],
        ['Key Age', user.key_age_days > 0 ? `${user.key_age_days} ngày` : 'N/A'],
    ].filter(([_, v]) => v !== 'N/A' && v !== 'No' && v !== undefined);

    const alerts = user.alerts || [];

    body.innerHTML = `
        <div style="margin-bottom:8px">
            ${fields.map(([label, val]) =>
                `<div class="modal-field">
                    <span class="modal-field-label">${label}</span>
                    <span class="modal-field-value">${val}</span>
                </div>`
            ).join('')}
        </div>
        ${alerts.length > 0 ? `
        <div class="modal-alerts">
            <h3>📋 Risk Alerts</h3>
            ${alerts.map(a => `<div class="alert-item">${a}</div>`).join('')}
        </div>` : ''}
        ${user.notes ? `
        <div style="margin-top:16px;padding:12px;background:var(--bg-input);border-radius:8px;font-size:0.85rem;color:var(--text-secondary)">
            📝 ${user.notes}
        </div>` : ''}
    `;

    modal.classList.add('open');
}

function closeModal() {
    document.getElementById('modal-overlay')?.classList.remove('open');
}

document.addEventListener('keydown', e => {
    if (e.key === 'Escape') closeModal();
});

// ─── Export ───────────────────────────────────────────────
function exportJSON() {
    if (!currentData) return;
    const blob = new Blob([JSON.stringify(currentData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `privilege_audit_${new Date().toISOString().slice(0,10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
    showToast('📥 Đang tải xuống file JSON...');
}

function refreshData() {
    showToast('🔄 Đang tải lại dữ liệu...');
    loadData();
}

// ─── Toast ────────────────────────────────────────────────
function showToast(message, duration = 3000) {
    const container = document.getElementById('toast-container');
    const toast = document.createElement('div');
    toast.className = 'toast';
    toast.textContent = message;
    container.appendChild(toast);
    setTimeout(() => {
        toast.style.opacity = '0';
        toast.style.transform = 'translateX(100%)';
        toast.style.transition = 'all 0.3s ease';
        setTimeout(() => toast.remove(), 300);
    }, duration);
}

// ─── Demo Data ────────────────────────────────────────────
function getDemoData() {
    const now = new Date().toISOString();
    const daysAgo = (n) => new Date(Date.now() - n * 864e5).toISOString();

    return {
        generated_at: now,
        systems: [
            {
                system: 'linux',
                summary: { total_privileged_users: 11, inactive_users: 4, critical_users: 3 },
                users: [
                    { username: 'john.doe',     privilege_source: ['sudoers','group:wheel'], full_access: true, nopasswd: true,  last_login: daysAgo(1),   days_inactive: 1,   risk_level: 'LOW',      alerts: [],                                                              notes: 'Active senior sysadmin' },
                    { username: 'jane.smith',   privilege_source: ['sudoers','group:sudo'],  full_access: false,nopasswd: false, last_login: daysAgo(3),   days_inactive: 3,   risk_level: 'LOW',      alerts: [],                                                              notes: 'DevOps lead' },
                    { username: 'michael.lee',  privilege_source: ['sudoers','group:wheel'], full_access: false,nopasswd: false, last_login: daysAgo(52),  days_inactive: 52,  risk_level: 'HIGH',     alerts: ['⚠️ Không hoạt động 52 ngày'],                                  notes: 'On extended leave' },
                    { username: 'devops01',     privilege_source: ['sudoers'],               full_access: false,nopasswd: true,  last_login: daysAgo(0),   days_inactive: 0,   risk_level: 'MEDIUM',   alerts: ['🔓 NOPASSWD sudo'],                                            notes: 'CI/CD account' },
                    { username: 'admin_old',    privilege_source: ['sudoers','group:wheel'], full_access: true, nopasswd: false, last_login: daysAgo(202), days_inactive: 202, risk_level: 'CRITICAL', alerts: ['⛔ Không hoạt động 202 ngày','🔑 Full sudo access'],            notes: 'Former employee!' },
                    { username: 'test_admin',   privilege_source: ['sudoers','group:sudo'],  full_access: true, nopasswd: true,  last_login: daysAgo(103), days_inactive: 103, risk_level: 'CRITICAL', alerts: ['⛔ Không hoạt động 103 ngày','🔑 Full sudo','🔓 NOPASSWD'],    notes: 'Test account with full sudo' },
                    { username: 'sysadmin2019', privilege_source: ['sudoers','group:wheel'], full_access: true, nopasswd: false, last_login: daysAgo(371), days_inactive: 371, risk_level: 'CRITICAL', alerts: ['⛔ Không hoạt động 371 ngày','🔑 Full sudo - nên disable ngay'], notes: 'Inactive 371 days!' },
                    { username: 'backup_agent', privilege_source: ['sudoers'],               full_access: false,nopasswd: true,  last_login: daysAgo(1),   days_inactive: 1,   risk_level: 'MEDIUM',   alerts: ['🔓 NOPASSWD sudo'],                                            notes: 'Backup service' },
                    { username: 'deploy_svc',   privilege_source: ['sudoers','group:wheel'], full_access: false,nopasswd: true,  last_login: daysAgo(6),   days_inactive: 6,   risk_level: 'MEDIUM',   alerts: ['🔓 NOPASSWD sudo'],                                            notes: 'Deploy service' },
                    { username: 'helpdesk',     privilege_source: ['group:wheel'],           full_access: false,nopasswd: false, last_login: daysAgo(2),   days_inactive: 2,   risk_level: 'LOW',      alerts: [],                                                              notes: 'Limited sudo' },
                    { username: 'monitoring',   privilege_source: ['sudoers'],               full_access: false,nopasswd: true,  last_login: daysAgo(0),   days_inactive: 0,   risk_level: 'LOW',      alerts: [],                                                              notes: 'Monitoring service' },
                ]
            },
            {
                system: 'active_directory',
                domain: 'CORP.LOCAL',
                summary: { total_privileged_users: 7, inactive_users: 4, critical_users: 3 },
                users: [
                    { username: 'alice.nguyen',    display_name: 'Alice Nguyen', privilege_groups: ['Domain Admins'],                             last_logon: daysAgo(1),   days_inactive: 1,   risk_level: 'LOW',      alerts: [], email: 'alice@corp.local', account_enabled: true },
                    { username: 'bob.tran',        display_name: 'Bob Tran',     privilege_groups: ['Domain Admins','Enterprise Admins'],         last_logon: daysAgo(67),  days_inactive: 67,  risk_level: 'HIGH',     alerts: ['⚠️ Không hoạt động 67 ngày','🚨 2 nhóm đặc quyền cao'], email: 'bob@corp.local', account_enabled: true },
                    { username: 'charlie.pham',    display_name: 'Charlie Pham', privilege_groups: ['Domain Admins','Schema Admins','Enterprise Admins'], last_logon: daysAgo(324), days_inactive: 324, risk_level: 'CRITICAL', alerts: ['⛔ Không hoạt động 324 ngày','🚨 3 nhóm đặc quyền cao!'], email: 'charlie@corp.local', account_enabled: true },
                    { username: 'diana.le',        display_name: 'Diana Le',     privilege_groups: ['Backup Operators'],                         last_logon: daysAgo(42),  days_inactive: 42,  risk_level: 'MEDIUM',   alerts: ['⚠️ Không hoạt động 42 ngày'], email: 'diana@corp.local', account_enabled: true },
                    { username: 'svc_backup',      display_name: 'Backup SVC',   privilege_groups: ['Backup Operators'],                         last_logon: daysAgo(1),   days_inactive: 1,   risk_level: 'LOW',      alerts: [], account_enabled: true },
                    { username: 'admin_temp2024',  display_name: 'Temp Admin',   privilege_groups: ['Domain Admins'],                            last_logon: daysAgo(172), days_inactive: 172, risk_level: 'CRITICAL', alerts: ['⛔ Không hoạt động 172 ngày','⚡ Tài khoản temp chưa xóa'], email: 'temp@corp.local', account_enabled: true },
                    { username: 'erik.hoang',      display_name: 'Erik Hoang',   privilege_groups: ['Domain Admins'],                            last_logon: daysAgo(2),   days_inactive: 2,   risk_level: 'LOW',      alerts: [], email: 'erik@corp.local', account_enabled: true },
                ]
            },
            {
                system: 'aws_iam',
                summary: { total_iam_users: 7, total_privileged_users: 5, inactive_privileged_users: 3, critical_users: 2, admins_without_mfa: 3 },
                users: [
                    { username: 'admin-alice',     has_admin_access: true,  mfa_active: true,  access_key_1_active: true,  access_key_2_active: false, key_age_days: 172, days_inactive: 2,   risk_level: 'MEDIUM',   alerts: ['🗝️ Access key chưa rotate 172 ngày'], attached_policies: ['AdministratorAccess'], groups: ['Administrators'], notes: 'Active admin với MFA' },
                    { username: 'bob-devops',      has_admin_access: true,  mfa_active: false, access_key_1_active: true,  access_key_2_active: false, key_age_days: 201, days_inactive: 62,  risk_level: 'HIGH',     alerts: ['⚠️ Không hoạt động 62 ngày','🔓 Không có MFA','🗝️ Key cũ 201 ngày'], attached_policies: ['AdministratorAccess'], groups: ['Administrators'], notes: 'No MFA - inactive 62d' },
                    { username: 'charlie-admin',   has_admin_access: true,  mfa_active: false, access_key_1_active: true,  access_key_2_active: true,  key_age_days: 811, days_inactive: 233, risk_level: 'CRITICAL', alerts: ['⛔ Không hoạt động 233 ngày','🔓 Không có MFA','🔑🔑 2 active keys','🗝️ Key chưa rotate 811 ngày'], attached_policies: ['AdministratorAccess','PowerUserAccess'], groups: ['Administrators'], notes: 'CRITICAL: inactive + no MFA + 2 keys' },
                    { username: 'root-backup-2021',has_admin_access: true,  mfa_active: false, access_key_1_active: true,  access_key_2_active: true,  key_age_days: 1937,days_inactive: 1467,risk_level: 'CRITICAL', alerts: ['⛔ Không hoạt động 1467 ngày!','🔓 Không có MFA','🔑🔑 2 active keys','🗝️ Key 1937 ngày chưa rotate'], attached_policies: ['AdministratorAccess'], groups: ['Administrators'], notes: 'Inactive 4+ YEARS - should be deleted!' },
                    { username: 'erik-temp',       has_admin_access: true,  mfa_active: false, access_key_1_active: true,  access_key_2_active: false, key_age_days: 80,  days_inactive: 77,  risk_level: 'HIGH',     alerts: ['⚠️ Không hoạt động 77 ngày','🔓 Không có MFA','👑 AdministratorAccess'], attached_policies: ['AdministratorAccess'], groups: ['Administrators'], notes: 'Temp user with Admin, inactive 77d' },
                ]
            }
        ],
        log_analysis: {
            total_sudo_events: 47,
            total_ssh_logins: 23,
            suspicious_accounts: ['sysadmin2019', 'root'],
            failed_login_accounts: { sysadmin2019: 8, root: 15 }
        }
    };
}

// ─── Inject Row Animation CSS ─────────────────────────────
const style = document.createElement('style');
style.textContent = `
@keyframes fade-in-row {
    from { opacity: 0; transform: translateY(8px); }
    to { opacity: 1; transform: translateY(0); }
}
`;
document.head.appendChild(style);

// ─── Init ─────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', () => {
    loadData();
});
